### ISSUE TITLE
could not connect to server: No such file or directory

### ISSUE THREAD

**Issue by nonunknown** [jtv/libpqxx#513]
Using: Manjaro Linux

error when trying to connect:
```
terminate called after throwing an instance of 'pqxx::broken_connection'
  what():  could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/run/postgresql/.s.PGSQL.5432"?

```

I was reading the docker logs:

![image](https://user-images.githubusercontent.com/58845030/146555704-fe075610-9b29-4184-93a9-3e7f2a2f49dd.png)

Seems the sock is being created at `/var/run` by the docker while `libpqxx` looks at: `/run` how I can solve that?

PS: connecting via `psql` command works fine!

**Comment by jtv** [comment]
Pass the correct socket path as the database "host," either in the
connection string or in the PGHOST variable.  The underlying C library will
recognise it as a socket path by the leading slash.

**Comment by nonunknown** [comment]
you mean like this?
![image](https://user-images.githubusercontent.com/58845030/146560346-6462e6bb-be15-46e5-b986-4530f1788ebe.png)

if so, the same error has appeared :/

**Comment by jtv** [comment]
Yes, that looks like what I expected to solve the problem.  Of course the
port number is meaningless if you're connecting to a Unix domain socket,
but I would expect it to be ignored when you pass a path as the host.

Do you get the same problem when you try to connect to the database using
psql instead?

**Comment by nonunknown** [comment]
yep

![image](https://user-images.githubusercontent.com/58845030/146566744-5a1c93af-9f1a-4b9b-af40-48303d073fae.png)

**Comment by KayEss** [comment]
If you're running Postgres inside docker and you want to connect to the unix domain socket then you have to share part of the host file system into the container. The docker container runs its own filesystem that isn't directly accessible from the host. You can look up the `-v` option for `docker run` to see how to share a folder between host and container. For running a program on the host you'll need to use the host path. Note that it may be non-standard -- the container should document what path it is using.

It is quite unusual to access a containerised postgres instance through a unix domain socket, normally the container exposes the standard port, but it will be mapped to another port on your host -- docker will tell you what the port mappings are (you should find it in the output of `docker container inspect <container-guid>`).

If you're trying to run your program inside the docker container alongside posgres, then you'll need to understand the init system (if any) that was shipped with the container running postgres -- trying to do this is almost certainly a bad idea though.

**Comment by nonunknown** [comment]
I'm using docker-compose and accessing it through my c++ program in my host OS.

docker-compose.yml:
```
version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: jd
      POSTGRES_DB: test

    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - sql-net
      
  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@email.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "16543:80"
    depends_on:
      - database
    networks:
      - sql-net

networks: 
  sql-net:
    driver: bridge

```
